### ISSUE TITLE
Last merged PR erase previous change

### ISSUE THREAD

**Issue by achaussier** [ahuffman/ansible-sudoers#10]
Hello,

The #8 PR has erased at least the #6 feature, perhaps another, but I don't have time today to review all the changes, sorry.

Do you want an another PR to reintegrate the changes ?

**Comment by wtcross** [comment]
Hi @achaussier, this must have happened while handling merging of some other things. Sorry that I missed it during review. Would you mind creating another PR? Thanks for the flexibility.

**Comment by achaussier** [comment]
Hello,

#11 must re-apply previous changes, and fix README style also :)

Can you take some time to see #9 and set a version management for this role please.

Thanks
