### ISSUE TITLE
Role nuked my /etc/sudoers.d, yet doco states it shouldn't have

### ISSUE THREAD

**Issue by lingfish** [ahuffman/ansible-sudoers#19]
So, as the title says.

`sudoer_separate_specs` defaults to true, and the doco states it should not nuke the directory contents, but mine did at the task `Remove separate sudoer specs that are not authorized`.

I think I'm meant to do something with `authorized_sudoer_specs`?  Needs to be documented better maybe?

**Comment by wtcross** [comment]
#20 improved testing around the role and added some lines to the docs.
