### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by achaussier** [ahuffman/ansible-sudoers#9]
Hello,

I think to have a better change management, this role should be driven with releases and/or tags using the semantic versioning (ex: 0.1.0) ?

What do you think about that ? If you're agree, can you set the first release/tag please ?

Thanks

**Comment by wtcross** [comment]
I think this is a great idea. I'll create the first tag as `1.0.0`.

**Comment by wtcross** [comment]
I just pushed it out. Previously I've been using the commit id, but usually do prefer tags. Closing this issue.
